# =========================================================
# Markdownlint 配置文件
# 用于 Neovim 中的 Markdown 代码检查
# 更宽松的规则配置，减少不必要的警告
# =========================================================

# 默认启用所有规则
default: true

# 禁用或调整特定规则
# 规则列表: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD001 - 标题层级增量（允许跳级）
MD001: false

# MD003 - 标题样式（允许任何样式）
MD003:
  style: consistent

# MD004 - 无序列表样式（允许任何样式）
MD004:
  style: consistent

# MD007 - 无序列表缩进（4个空格）
MD007:
  indent: 4

# MD010 - 硬标签（允许在代码块中使用）
MD010:
  code_blocks: false

# MD012 - 多个连续空行（最多2行）
MD012:
  maximum: 2

# MD013 - 行长度限制（禁用，允许长行）
MD013: false

# MD024 - 重复标题（允许在不同层级）
MD024:
  siblings_only: true

# MD025 - 单个 H1 标题（禁用，允许多个）
MD025: false

# MD026 - 标题末尾标点（允许）
MD026:
  punctuation: ".,;:!"

# MD033 - 内联 HTML（允许）
MD033: false

# MD034 - 裸 URL（允许）
MD034: false

# MD036 - 强调代替标题（禁用）
MD036: false

# MD040 - 代码块语言（建议但不强制）
MD040: false

# MD041 - 文件必须以 H1 开头（禁用）
MD041: false

# MD046 - 代码块样式（围栏式）
MD046:
  style: fenced

# MD049 - 强调样式（下划线或星号，保持一致）
MD049:
  style: consistent

# MD050 - 加粗样式（保持一致）
MD050:
  style: consistent
